spring.application.name=accessbasededonnees
spring.datasource.url=jdbc:postgresql://localhost:5432/projet_formulaire
spring.datasource.username=levi
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=TRACE
# Configuration JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# token secret
security.jwt.token.secret-key=

# access token validity
security.jwt.token.expiration=900000

spring.jpa.defer-datasource-initialization=true

# refresh the token validity 7 days
security.jwt.token.refresh-expiration=604800000

###  properties for rotation
security.jwt.token.rotation-enabled=false

# previous secret key
security.jwt.token.previous-secret-key=

# interval to rotate the secret key
security.jwt.token.rotation-period=518400000


# seven days
security.jwt.token.refresh-additional-time-validity=604800000

# 15 minutes
security.jwt.token.access-additional-time-validity=180000
  #900000

# 1 day
security.jwt.token.refresh-threshold=86400000



# Active Token
redis.active-token.host=localhost
redis.active-token.port=6379
redis.active-token.database=0
redis.active-token.username=default
redis.active-token.password=1234

# Revoked Token
redis.revoked-token.host=localhost
redis.revoked-token.port=6379
redis.revoked-token.database=1
redis.revoked-token.username=default
redis.revoked-token.password=1234

spring.data.redis.repositories.enabled=false






